export enum ActionTypes{
    ADD_USER = "ADD_USER",
    REMOVE_USER = "REMOVE_USER",
    LOGOUT = "LOGOUT",
    REFRESH = "REFRESH",
    SET_USERFETCHED="SET_USERFETCHED",
    ADD_LOCALTRACKS = "ADD_LOCALTRACKS",
    ADD_REMOTE_USERS = "ADD_REMOTE_USERS",
    ADD_COURSE_DATA="ADD_COURSE_DATA"

}