export enum ActionTypes{
    ADD_USER = "ADD_USER",
    REMOVE_USER = "REMOVE_USER",
    LOGOUT = "LOGOUT",
    REFRESH = "REFRESH",
    SET_USERFETCHED="SET_USERFETCHED",
    ADD_LOCALTRACKS = "ADD_LOCALTRACKS"

}